2024-11-04 18:04:00.507 | INFO     | __main__:serve:67 - 启动服务：192.168.0.102:2332
2024-11-04 18:04:00.511 | INFO     | __main__:serve:69 - 服务注册开始
2024-11-04 18:04:00.515 | INFO     | common.register.consul:register_grpc:61 - http://192.168.0.102:2332/health
2024-11-04 18:04:00.516 | INFO     | common.register.consul:register_grpc:63 - HTTP健康检查服务注册成功
2024-11-04 18:04:31.709 | ERROR    | grpc._server:_call_behavior:610 - An error has been caught in function '_call_behavior', process 'MainProcess' (9156), thread 'ThreadPoolExecutor-0_0' (26116):
Traceback (most recent call last):

  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 7285, in get
    return clone.execute(database)[0]
           │     │       └ None
           │     └ <function BaseQuery.execute at 0x000001A2BAFA0F40>
           └ <peewee.ModelSelect object at 0x000001A2BB9ABF80>
  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 4581, in __getitem__
    return self.row_cache[item]
           │    │         └ 0
           │    └ []
           └ <peewee.ModelObjectCursorWrapper object at 0x000001A2BB9ABFB0>

IndexError: list index out of range


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\Miniconda3\Lib\threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001A2B82119E0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
  File "D:\Miniconda3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001A2B82116C0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
  File "D:\Miniconda3\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
    │    │        │    └ (<weakref at 0x000001A2BB9CC860; to 'ThreadPoolExecutor' at 0x000001A2BB055EE0>, <_queue.SimpleQueue object at 0x000001A2BB72...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
    │    └ <function _worker at 0x000001A2BB74F240>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
  File "D:\Miniconda3\Lib\concurrent\futures\thread.py", line 92, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001A2BB74F380>
    └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9ABDA0>
  File "D:\Miniconda3\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9ABDA0>
             │    │   │    └ (<function _unary_response_in_pool at 0x000001A2BB9B6840>, <grpc._cython.cygrpc.RequestCallEvent object at 0x000001A2BB9CCF90...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9ABDA0>
             │    └ <built-in method run of _contextvars.Context object at 0x000001A2BB9BF400>
             └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9ABDA0>
  File "E:\workspace\Mall_srv\venv\Lib\site-packages\grpc\_server.py", line 793, in _unary_response_in_pool
    response, proceed = _call_behavior(
                        └ <function _call_behavior at 0x000001A2BB9B63E0>
> File "E:\workspace\Mall_srv\venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x000001A2BB9ABDD0>
                           │        └ goods: 421
                           │          
                           └ <bound method UserFavServicer.GetUserFavDetail of <userop_srv.handler.userfav.userfav.UserFavServicer object at 0x000001A2BB9...

  File "E:\workspace\Mall_srv\userop_srv\handler\userfav\userfav.py", line 63, in GetUserFavDetail
    userfav = UserFav.get(UserFav.user == request.userId, UserFav.goods == request.goods)
              │       │   │       │       │               │       │        └ goods: 421
              │       │   │       │       │               │       │          
              │       │   │       │       │               │       └ <peewee.FieldAccessor object at 0x000001A2BB02A960>
              │       │   │       │       │               └ <Model: UserFav>
              │       │   │       │       └ goods: 421
              │       │   │       │         
              │       │   │       └ <peewee.FieldAccessor object at 0x000001A2BAEFBB00>
              │       │   └ <Model: UserFav>
              │       └ <classmethod(<function Model.get at 0x000001A2BAFD74C0>)>
              └ <Model: UserFav>

  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 6833, in get
    return sq.get()
           │  └ <function BaseModelSelect.get at 0x000001A2BAFD9B20>
           └ <peewee.ModelSelect object at 0x000001A2BB9ABCB0>
  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 7288, in get
    raise self.model.DoesNotExist('%s instance matching query does '
          │    │     └ <class 'userop_srv.model.models.UserFavDoesNotExist'>
          │    └ <Model: UserFav>
          └ <peewee.ModelSelect object at 0x000001A2BB9ABCB0>

userop_srv.model.models.UserFavDoesNotExist: <Model: UserFav> instance matching query does not exist:
SQL: SELECT `t1`.`add_time`, `t1`.`is_deleted`, `t1`.`update_time`, `t1`.`user`, `t1`.`goods` FROM `userfav` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`user` = %s)) AND (`t1`.`goods` = %s)) LIMIT %s OFFSET %s
Params: [False, 0, 421, 1, 0]
2024-11-04 18:06:59.616 | ERROR    | grpc._server:_call_behavior:610 - An error has been caught in function '_call_behavior', process 'MainProcess' (9156), thread 'ThreadPoolExecutor-0_0' (26116):
Traceback (most recent call last):

  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 7285, in get
    return clone.execute(database)[0]
           │     │       └ None
           │     └ <function BaseQuery.execute at 0x000001A2BAFA0F40>
           └ <peewee.ModelSelect object at 0x000001A2BB9DD7F0>
  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 4581, in __getitem__
    return self.row_cache[item]
           │    │         └ 0
           │    └ []
           └ <peewee.ModelObjectCursorWrapper object at 0x000001A2BB9AA480>

IndexError: list index out of range


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\Miniconda3\Lib\threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001A2B82119E0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
  File "D:\Miniconda3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001A2B82116C0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
  File "D:\Miniconda3\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
    │    │        │    └ (<weakref at 0x000001A2BB9CC860; to 'ThreadPoolExecutor' at 0x000001A2BB055EE0>, <_queue.SimpleQueue object at 0x000001A2BB72...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
    │    └ <function _worker at 0x000001A2BB74F240>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
  File "D:\Miniconda3\Lib\concurrent\futures\thread.py", line 92, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001A2BB74F380>
    └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9DDC70>
  File "D:\Miniconda3\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9DDC70>
             │    │   │    └ (<function _unary_response_in_pool at 0x000001A2BB9B6840>, <grpc._cython.cygrpc.RequestCallEvent object at 0x000001A2BB9CC630...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9DDC70>
             │    └ <built-in method run of _contextvars.Context object at 0x000001A2BB9BD9C0>
             └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9DDC70>
  File "E:\workspace\Mall_srv\venv\Lib\site-packages\grpc\_server.py", line 793, in _unary_response_in_pool
    response, proceed = _call_behavior(
                        └ <function _call_behavior at 0x000001A2BB9B63E0>
> File "E:\workspace\Mall_srv\venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x000001A2BB9DE720>
                           │        └ goods: 421
                           │          
                           └ <bound method UserFavServicer.GetUserFavDetail of <userop_srv.handler.userfav.userfav.UserFavServicer object at 0x000001A2BB9...

  File "E:\workspace\Mall_srv\userop_srv\handler\userfav\userfav.py", line 63, in GetUserFavDetail
    userfav = UserFav.get(UserFav.user == request.userId, UserFav.goods == request.goods)
              │       │   │       │       │               │       │        └ goods: 421
              │       │   │       │       │               │       │          
              │       │   │       │       │               │       └ <peewee.FieldAccessor object at 0x000001A2BB02A960>
              │       │   │       │       │               └ <Model: UserFav>
              │       │   │       │       └ goods: 421
              │       │   │       │         
              │       │   │       └ <peewee.FieldAccessor object at 0x000001A2BAEFBB00>
              │       │   └ <Model: UserFav>
              │       └ <classmethod(<function Model.get at 0x000001A2BAFD74C0>)>
              └ <Model: UserFav>

  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 6833, in get
    return sq.get()
           │  └ <function BaseModelSelect.get at 0x000001A2BAFD9B20>
           └ <peewee.ModelSelect object at 0x000001A2BB9DD940>
  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 7288, in get
    raise self.model.DoesNotExist('%s instance matching query does '
          │    │     └ <class 'userop_srv.model.models.UserFavDoesNotExist'>
          │    └ <Model: UserFav>
          └ <peewee.ModelSelect object at 0x000001A2BB9DD940>

userop_srv.model.models.UserFavDoesNotExist: <Model: UserFav> instance matching query does not exist:
SQL: SELECT `t1`.`add_time`, `t1`.`is_deleted`, `t1`.`update_time`, `t1`.`user`, `t1`.`goods` FROM `userfav` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`user` = %s)) AND (`t1`.`goods` = %s)) LIMIT %s OFFSET %s
Params: [False, 0, 421, 1, 0]
2024-11-04 18:09:12.003 | ERROR    | grpc._server:_call_behavior:610 - An error has been caught in function '_call_behavior', process 'MainProcess' (9156), thread 'ThreadPoolExecutor-0_0' (26116):
Traceback (most recent call last):

  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 7285, in get
    return clone.execute(database)[0]
           │     │       └ None
           │     └ <function BaseQuery.execute at 0x000001A2BAFA0F40>
           └ <peewee.ModelSelect object at 0x000001A2BBBB8050>
  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 4581, in __getitem__
    return self.row_cache[item]
           │    │         └ 0
           │    └ []
           └ <peewee.ModelObjectCursorWrapper object at 0x000001A2BB9DC050>

IndexError: list index out of range


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\Miniconda3\Lib\threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001A2B82119E0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
  File "D:\Miniconda3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001A2B82116C0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
  File "D:\Miniconda3\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
    │    │        │    └ (<weakref at 0x000001A2BB9CC860; to 'ThreadPoolExecutor' at 0x000001A2BB055EE0>, <_queue.SimpleQueue object at 0x000001A2BB72...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
    │    └ <function _worker at 0x000001A2BB74F240>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 26116)>
  File "D:\Miniconda3\Lib\concurrent\futures\thread.py", line 92, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001A2BB74F380>
    └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9DFC20>
  File "D:\Miniconda3\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9DFC20>
             │    │   │    └ (<function _unary_response_in_pool at 0x000001A2BB9B6840>, <grpc._cython.cygrpc.RequestCallEvent object at 0x000001A2BB9CCE50...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9DFC20>
             │    └ <built-in method run of _contextvars.Context object at 0x000001A2BB9BF400>
             └ <concurrent.futures.thread._WorkItem object at 0x000001A2BB9DFC20>
  File "E:\workspace\Mall_srv\venv\Lib\site-packages\grpc\_server.py", line 793, in _unary_response_in_pool
    response, proceed = _call_behavior(
                        └ <function _call_behavior at 0x000001A2BB9B63E0>
> File "E:\workspace\Mall_srv\venv\Lib\site-packages\grpc\_server.py", line 610, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x000001A2BB9DFD40>
                           │        └ goods: 421
                           │          
                           └ <bound method UserFavServicer.GetUserFavDetail of <userop_srv.handler.userfav.userfav.UserFavServicer object at 0x000001A2BB9...

  File "E:\workspace\Mall_srv\userop_srv\handler\userfav\userfav.py", line 63, in GetUserFavDetail
    userfav = UserFav.get(UserFav.user == request.userId, UserFav.goods == request.goods)
              │       │   │       │       │               │       │        └ goods: 421
              │       │   │       │       │               │       │          
              │       │   │       │       │               │       └ <peewee.FieldAccessor object at 0x000001A2BB02A960>
              │       │   │       │       │               └ <Model: UserFav>
              │       │   │       │       └ goods: 421
              │       │   │       │         
              │       │   │       └ <peewee.FieldAccessor object at 0x000001A2BAEFBB00>
              │       │   └ <Model: UserFav>
              │       └ <classmethod(<function Model.get at 0x000001A2BAFD74C0>)>
              └ <Model: UserFav>

  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 6833, in get
    return sq.get()
           │  └ <function BaseModelSelect.get at 0x000001A2BAFD9B20>
           └ <peewee.ModelSelect object at 0x000001A2BB9DFF50>
  File "E:\workspace\Mall_srv\venv\Lib\site-packages\peewee.py", line 7288, in get
    raise self.model.DoesNotExist('%s instance matching query does '
          │    │     └ <class 'userop_srv.model.models.UserFavDoesNotExist'>
          │    └ <Model: UserFav>
          └ <peewee.ModelSelect object at 0x000001A2BB9DFF50>

userop_srv.model.models.UserFavDoesNotExist: <Model: UserFav> instance matching query does not exist:
SQL: SELECT `t1`.`add_time`, `t1`.`is_deleted`, `t1`.`update_time`, `t1`.`user`, `t1`.`goods` FROM `userfav` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`user` = %s)) AND (`t1`.`goods` = %s)) LIMIT %s OFFSET %s
Params: [False, 0, 421, 1, 0]
2024-11-04 18:12:33.512 | INFO     | __main__:on_exit:27 - 注销<frame at 0x000001A2BB9A6A40, file 'D:\\Miniconda3\\Lib\\threading.py', line 359, code wait>服务
2024-11-04 18:12:33.520 | ERROR    | common.register.consul:unregister:75 - 注销失败:404
2024-11-04 18:12:33.521 | INFO     | __main__:on_exit:29 - 注销成功
